name: Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: [stable, nightly]
        include:
        - os: macos-latest
          rust-version: stable
        - os: windows-latest
          rust-version: stable
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Cache node modules
      uses: actions/cache@v2
      id: node-modules
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-
    - run: npm install
    - name: Build frontend
      run: npm run build
    - name: Set up Rust ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      id: rustup
      with:
        toolchain: ${{ matrix.rust-version }}
        override: true
    - name: Build
      run: |
        cargo build --verbose
    - name: Run tests
      run: cargo test -- --show-output
    - name: Run program
      run: cargo run -- process test.json test.log
